import { Listing, ListingInquiry, SponsorProfile, UserProfile } from "@/lib/types";

export const mockUsers: UserProfile[] = [
  {
    id: "admin-1",
    role: "admin",
    fullName: "Operations Lead",
    email: "ops@credex.com",
    status: "active",
  },
  {
    id: "sponsor-1",
    role: "sponsor",
    fullName: "Nina Alvarez",
    email: "nina@ridgecapital.com",
    status: "active",
  },
  {
    id: "sponsor-2",
    role: "sponsor",
    fullName: "Marcus Chen",
    email: "marcus@harborequity.com",
    status: "active",
  },
  {
    id: "investor-1",
    role: "investor",
    fullName: "Daniel Brooks",
    email: "daniel@example.com",
    status: "active",
  },
];

export const mockSponsors: SponsorProfile[] = [
  {
    userId: "sponsor-1",
    companyName: "Ridge Capital Partners",
    bio: "Sun Belt multifamily operator focused on operational lift, tenant retention, and disciplined portfolio management.",
    trackRecordSummary: "12 full-cycle exits, 2,480 units, 18.7% realized IRR across completed investments.",
    verificationStatus: "verified",
  },
  {
    userId: "sponsor-2",
    companyName: "Harbor Equity Group",
    bio: "Multifamily operator with a conservative underwriting style, steady communication habits, and a focus on resilient growth corridors.",
    trackRecordSummary: "9 full-cycle exits, 1,930 units, 2.1x average equity multiple on realized investments.",
    verificationStatus: "verified",
  },
];

export const mockListings: Listing[] = [
  {
    id: "listing-1",
    sponsorId: "sponsor-1",
    sponsorName: "Ridge Capital Partners",
    title: "Sun Belt value-add",
    slug: "oakline-residences",
    city: "Phoenix",
    state: "AZ",
    summary: "Known for repeatable Sun Belt execution, operational discipline, and clear reporting through renovation-heavy business plans.",
    marketStory: "Tends to focus on markets with job growth, rent durability, and room for operational improvement without relying on aggressive assumptions.",
    propertyType: "multifamily",
    strategy: "Value-add",
    marketFocus: "Sun Belt growth",
    units: 198,
    targetIrr: 18,
    equityMultiple: 2.1,
    cashOnCash: 7.4,
    holdPeriodYears: 5,
    minimumInvestment: 50000,
    yearBuilt: 2002,
    status: "published",
    coverTone: "sunrise",
    publishedAt: "2026-03-10",
  },
  {
    id: "listing-2",
    sponsorId: "sponsor-2",
    sponsorName: "Harbor Equity Group",
    title: "Suburban core-plus",
    slug: "harbor-north-flats",
    city: "Charlotte",
    state: "NC",
    summary: "Often operates in migration markets where conservative leverage and steady execution matter more than headline upside.",
    marketStory: "Leans toward suburban locations with durable occupancy, employer depth, and business plans that can perform through choppier cycles.",
    propertyType: "multifamily",
    strategy: "Core-plus",
    marketFocus: "Migration markets",
    units: 262,
    targetIrr: 16.5,
    equityMultiple: 1.9,
    cashOnCash: 6.8,
    holdPeriodYears: 5,
    minimumInvestment: 75000,
    yearBuilt: 1998,
    status: "published",
    coverTone: "marine",
    publishedAt: "2026-03-15",
  },
  {
    id: "listing-3",
    sponsorId: "sponsor-1",
    sponsorName: "Ridge Capital Partners",
    title: "Infill repositioning",
    slug: "crescent-yard",
    city: "Tampa",
    state: "FL",
    summary: "Best known for infill repositioning work that depends on hands-on asset management and careful operating follow-through.",
    marketStory: "Usually targets constrained submarkets where supply is limited and execution quality can matter more than financial engineering.",
    propertyType: "multifamily",
    strategy: "Value-add",
    marketFocus: "Infill inflection",
    units: 144,
    targetIrr: 17.2,
    equityMultiple: 2,
    cashOnCash: 7.1,
    holdPeriodYears: 4,
    minimumInvestment: 50000,
    yearBuilt: 1994,
    status: "published",
    coverTone: "terracotta",
    publishedAt: "2026-03-18",
  },
  {
    id: "listing-4",
    sponsorId: "sponsor-2",
    sponsorName: "Harbor Equity Group",
    title: "Workforce housing focus",
    slug: "juniper-commons",
    city: "Nashville",
    state: "TN",
    summary: "Emphasizes stable cash flow, measured capex, and a sponsor style built around downside protection.",
    marketStory: "Typically operates in defensive workforce housing segments where basis discipline and cost control drive outcomes over time.",
    propertyType: "multifamily",
    strategy: "Workforce housing",
    marketFocus: "Defensive cash flow",
    units: 210,
    targetIrr: 15.8,
    equityMultiple: 1.8,
    cashOnCash: 6.3,
    holdPeriodYears: 5,
    minimumInvestment: 100000,
    yearBuilt: 2000,
    status: "submitted",
    coverTone: "cobalt",
    publishedAt: "2026-03-20",
  },
];

export const mockInquiries: ListingInquiry[] = [
  {
    id: "inq-1",
    listingId: "listing-1",
    listingTitle: "Oakline Residences",
    investorId: "investor-1",
    investorName: "Daniel Brooks",
    investorEmail: "daniel@example.com",
    message: "Interested in sponsor track record and debt terms before requesting docs.",
    status: "new",
    createdAt: "2026-03-20T17:20:00Z",
  },
];
