import { Listing, ListingInquiry, SponsorProfile, UserProfile } from "@/lib/types";

export const mockUsers: UserProfile[] = [
  {
    id: "admin-1",
    role: "admin",
    fullName: "Operations Lead",
    email: "ops@syndicatelane.com",
    status: "active",
  },
  {
    id: "sponsor-1",
    role: "sponsor",
    fullName: "Nina Alvarez",
    email: "nina@ridgecapital.com",
    status: "active",
  },
  {
    id: "sponsor-2",
    role: "sponsor",
    fullName: "Marcus Chen",
    email: "marcus@harborequity.com",
    status: "active",
  },
  {
    id: "investor-1",
    role: "investor",
    fullName: "Daniel Brooks",
    email: "daniel@example.com",
    status: "active",
  },
];

export const mockSponsors: SponsorProfile[] = [
  {
    userId: "sponsor-1",
    companyName: "Ridge Capital Partners",
    bio: "Sun Belt multifamily sponsor focused on operational lift and tenant-focused repositioning.",
    trackRecordSummary: "12 exits, 2,480 units, 18.7% realized IRR across closed deals.",
    verificationStatus: "verified",
  },
  {
    userId: "sponsor-2",
    companyName: "Harbor Equity Group",
    bio: "Value-add apartment acquisitions in growth corridors with conservative debt structures.",
    trackRecordSummary: "9 exits, 1,930 units, 2.1x average equity multiple on realized projects.",
    verificationStatus: "verified",
  },
];

export const mockListings: Listing[] = [
  {
    id: "listing-1",
    sponsorId: "sponsor-1",
    sponsorName: "Ridge Capital Partners",
    title: "Oakline Residences",
    slug: "oakline-residences",
    city: "Phoenix",
    state: "AZ",
    summary: "198-unit garden-style acquisition with classic interiors and near-term renovation upside.",
    marketStory: "Located inside a high-growth employment corridor with below-market in-place rents and recent comp growth above 6%.",
    propertyType: "multifamily",
    units: 198,
    targetIrr: 18,
    equityMultiple: 2.1,
    cashOnCash: 7.4,
    holdPeriodYears: 5,
    minimumInvestment: 50000,
    yearBuilt: 2002,
    status: "published",
    coverTone: "sunrise",
    publishedAt: "2026-03-10",
  },
  {
    id: "listing-2",
    sponsorId: "sponsor-2",
    sponsorName: "Harbor Equity Group",
    title: "Harbor North Flats",
    slug: "harbor-north-flats",
    city: "Charlotte",
    state: "NC",
    summary: "262-unit suburban asset positioned for exterior refresh and amenity upgrade.",
    marketStory: "Strong migration tailwinds, employer expansion nearby, and occupancy resilience through rate volatility.",
    propertyType: "multifamily",
    units: 262,
    targetIrr: 16.5,
    equityMultiple: 1.9,
    cashOnCash: 6.8,
    holdPeriodYears: 5,
    minimumInvestment: 75000,
    yearBuilt: 1998,
    status: "published",
    coverTone: "marine",
    publishedAt: "2026-03-15",
  },
  {
    id: "listing-3",
    sponsorId: "sponsor-1",
    sponsorName: "Ridge Capital Partners",
    title: "Crescent Yard",
    slug: "crescent-yard",
    city: "Tampa",
    state: "FL",
    summary: "144-unit infill community with mark-to-market rent upside and operational cleanup.",
    marketStory: "Walkable submarket with constrained new supply and healthy renter-by-necessity demand.",
    propertyType: "multifamily",
    units: 144,
    targetIrr: 17.2,
    equityMultiple: 2,
    cashOnCash: 7.1,
    holdPeriodYears: 4,
    minimumInvestment: 50000,
    yearBuilt: 1994,
    status: "published",
    coverTone: "terracotta",
    publishedAt: "2026-03-18",
  },
  {
    id: "listing-4",
    sponsorId: "sponsor-2",
    sponsorName: "Harbor Equity Group",
    title: "Juniper Commons",
    slug: "juniper-commons",
    city: "Nashville",
    state: "TN",
    summary: "210-unit workforce housing repositioning with conservative capex and staged rent growth.",
    marketStory: "Defensive basis with upside through unit interiors, amenity improvement, and expense management.",
    propertyType: "multifamily",
    units: 210,
    targetIrr: 15.8,
    equityMultiple: 1.8,
    cashOnCash: 6.3,
    holdPeriodYears: 5,
    minimumInvestment: 100000,
    yearBuilt: 2000,
    status: "submitted",
    coverTone: "cobalt",
    publishedAt: "2026-03-20",
  },
];

export const mockInquiries: ListingInquiry[] = [
  {
    id: "inq-1",
    listingId: "listing-1",
    listingTitle: "Oakline Residences",
    investorId: "investor-1",
    investorName: "Daniel Brooks",
    investorEmail: "daniel@example.com",
    message: "Interested in sponsor track record and debt terms before requesting docs.",
    status: "new",
    createdAt: "2026-03-20T17:20:00Z",
  },
];

